import { readStreamableValue } from "ai/rsc";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { FaAngleLeft } from "react-icons/fa";
import ReactMarkdown from "react-markdown";
import { analyzeQuery } from "../_actions/analyzeQuery";

export const Analysis = () => {
  const router = useRouter();
  const [output, setOutput] = useState<string>("");
  const [useAi, setUseAi] = useState<boolean | null>(null);

  useEffect(() => {
    const plan = window.localStorage.getItem("plan");
    const query = window.localStorage.getItem("query");

    if (!plan || !query) {
      router.push("/");
    }

    const preferences = JSON.parse(
      window.localStorage.getItem("supexplain_preferences") ?? "{}"
    );

    const ai = preferences.ai ?? false;

    setUseAi(ai);
    if (plan && query && ai) {
      let isMounted = true;

      analyzeQuery({ plan, query }).then(async (output) => {
        for await (const content of readStreamableValue(output)) {
          if (isMounted) {
            setOutput((prev) => (prev ?? "") + (content ?? ""));
          }
        }
      });

      return () => {
        isMounted = false;
      };
    }
  }, []);

  return (
    <div className="flex flex-col h-1/2 lg:h-full w-full lg:w-1/3 items-start justify-between px-4 lg:pl-4 lg:px-0 gap-y-4">
      <div className="flex w-full justify-between gap-x-8">
        <button
          className="flex items-center gap-x-2 text-sm border rounded px-2 py-1 shadow-sm hover:bg-gray-100"
          onClick={() => {
            router.push("/");
          }}
        >
          <FaAngleLeft /> Back
        </button>
        <p className="text-xs max-w-80 px-2 text-right text-gray-400 flex items-center gap-x-1 italic">
          This text is auto-generated by GPT-4o-mini. Please be careful while running any commands suggested by AI
        </p>
      </div>
      <div className="flex flex-col w-full h-full overflow-y-auto items-center justify-start text-start">
        {useAi == null ? null : useAi ? (
          <div className="prose pr-2 overflow-x-hidden break-words w-full h-full">
            <ReactMarkdown
              components={{
                hr: () => null,
              }}
            >
              {output}
            </ReactMarkdown>
          </div>
        ) : (
          <div className="text-sm h-full flex w-full text-center items-center justify-center text-gray-500">
            AI analysis is disabled
          </div>
        )}
      </div>
    </div>
  );
};
